### ISSUE TITLE
BUG 'Add to the Map' from `Project` context menu does not work and throws error

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#133]
See: https://youtu.be/Ibr-hJH25vg

## General Error Message
```
2022-10-18T20:56:27     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
```
## Python Error Message
```
2022-10-18T20:57:01     WARNING    Traceback (most recent call last):
              File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 213, in 
              self.add_context_menu_item(self.menu, 'Add To Map', 'add_to_map', lambda: self.add_db_item_to_map(model_item, model_data))
              File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 268, in add_db_item_to_map
              [build_mask_layer(mask) for mask in self.project.masks.values()]
              File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 268, in 
              [build_mask_layer(mask) for mask in self.project.masks.values()]
             TypeError: build_mask_layer() missing 1 required positional argument: 'mask'
             
```

**Comment by KellyMWhitehead** [comment]
This was fixed when we implemented the new map_manager (0.1.10).
