### ISSUE TITLE
QRiS 0.1.8 Also Fails on Install looking for `matplotlib.backends.backend_qt4agg`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#153]
Dejavu: https://youtu.be/5uOsaPRhZyg

Error:
```
Couldn't load plugin 'qris_deploy' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\__init__.py", line 40, in classFactory
    from .src.qris_toolbar import QRiSToolbar
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 41, in 
    from .view.frm_dockwidget import QRiSDockWidget
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 62, in 
    from .frm_stream_gage_docwidget import FrmStreamGageDocWidget
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_stream_gage_docwidget.py", line 25, in 
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

Python Path:
C:/PROGRA~1/QGIS32~2.3/apps/qgis/./python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~2.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.26.3\bin\python39.zip
C:\PROGRA~1\QGIS32~2.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib
C:\Program Files\QGIS 3.26.3\bin
C:\Users\joemw\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~2.3\apps\Python39
C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by joewheaton** [comment]
Exactly the same as #144

**Comment by philipbaileynar** [comment]
Visual Studio Code has a dangerous feature where it tries to guess what class/object you are referring to, and then unbeknownst to you it automatically imports that class. I found a couple more inadvertent references to matplotlib that VSC had added.


90c9023a16b4198c3a48538f201f7beac592effa
