### ISSUE TITLE
Centerline tool randomly fails

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#197]
I have a valley bottom shapefile that is segmented by stream, so I can run centerlines individually on each segment across the watershed.
The centerline tool will work on some sections and not others. It seems super random. This is the error I'm getting.

 Traceback (most recent call last):
              File "C:\Users/joshu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\centerlines.py", line 158, in finished
              if self.exception is None:
             AttributeError: 'CenterlineTask' object has no attribute 'exception'

As well as this in the log messages.

****An error has occurred while executing Python code:
            UnboundLocalError: local variable 'g_centerline_out' referenced before assignment
            Traceback (most recent call last):
              File "C:\Users/joshu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\centerlines.py", line 135, in run
              if g_centerline_out.isEmpty():
             UnboundLocalError: local variable 'g_centerline_out' referenced before assignment****

**Comment by KellyMWhitehead** [comment]
This specific error should now be fixed. I also improved the exception handling for centerlines a bit, hopefully will provide some better user feedback.

**Comment by philipbaileynar** [comment]
Closing until anyone raises issues with the CL tool.
