### ISSUE TITLE
2023-07-18T14:03:55     CRITICAL    Matplotlib is not at a sufficient version: 3.5.1

### ISSUE THREAD

**Issue by AldenShallcross** [Riverscapes/QRiS#223]
I'm unable to load projects into QRIS and recieve the following error messages.  

2023-07-18T14:03:55     CRITICAL    Matplotlib is not at a sufficient version: 3.5.1

2023-07-18T14:06:31     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 538, in update_database
              apply_db_migrations(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 138, in apply_db_migrations
              raise ex
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 123, in apply_db_migrations
              curs.execute('SELECT * FROM migrations WHERE file_name LIKE ?', [migration_file])
             sqlite3.OperationalError: no such table: migrations
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 404, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 413, in open_qris_project
              self.update_database(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 540, in update_database
              QtWidgets.QMessageBox.warning(self, 'Error Appling QRiS Database Migrations', str(ex))
             TypeError: warning(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'QRiSToolbar'
             
2023-07-18T14:07:53     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 538, in update_database
              apply_db_migrations(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 138, in apply_db_migrations
              raise ex
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 123, in apply_db_migrations
              curs.execute('SELECT * FROM migrations WHERE file_name LIKE ?', [migration_file])
             sqlite3.OperationalError: no such table: migrations
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 404, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 413, in open_qris_project
              self.update_database(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 540, in update_database
              QtWidgets.QMessageBox.warning(self, 'Error Appling QRiS Database Migrations', str(ex))
             TypeError: warning(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'QRiSToolbar'
             
2023-07-18T14:08:17     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 538, in update_database
              apply_db_migrations(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 138, in apply_db_migrations
              raise ex
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\model\project.py", line 123, in apply_db_migrations
              curs.execute('SELECT * FROM migrations WHERE file_name LIKE ?', [migration_file])
             sqlite3.OperationalError: no such table: migrations
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 404, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 413, in open_qris_project
              self.update_database(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 540, in update_database
              QtWidgets.QMessageBox.warning(self, 'Error Appling QRiS Database Migrations', str(ex))
             TypeError: warning(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'QRiSToolbar'

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar I continue to get this error as well even with 0.3.6: 
```
2023-12-27T13:19:55     CRITICAL    Matplotlib is not at a sufficient version: 3.5.1
```

Please help us at least with a Knowledge Base Article on a workaround (i.e. how to manually install Matplotlib using Python), or suggest a way forward. Users will find it discomforting when the first thing they see after installing QRiS plugin is a CRITICAL error log message that shows up every time.

**Comment by philipbaileynar** [comment]
I think we can remove the MatPlotLib dependency as a short term fix. 

It's infuriating because we would love to make our tools more visual by integrating charts in lots of places. But it boggles my mind that MatPlotLib - a ubiquitous Python package - is unavailable in certain versions of QGIS.

**Comment by KellyMWhitehead** [comment]
Matplotlib issues are now resolved.
