### ISSUE TITLE
Analysis dockable window failed to open with no sampling frame polygons

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#289]
1. Create project.
2. Add sample frame - BUT DO NOT DIGITIZE ANY FEATURES
3. Create a DCE with one layer - BUT DO NOT DIGITIZE ANY FEATURES
4. Create an analysis. Give it a name.
5. Right click on analysis and choose **Open**

Error!

I think this is because there are no sampling frame polygons. 

```
2023-12-15T17:26:49     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 292, in 
              self.add_context_menu_item(self.menu, 'Create New Analysis', 'new', lambda: self.add_analysis(model_item))
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 543, in add_analysis
              self.open_analysis(frm.analysis)
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 552, in open_analysis
              self.analysis_doc_widget.configure_analysis(self.project, analysis, None)
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 78, in configure_analysis
              self.build_table()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 108, in build_table
              self.load_table_values()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:30:56     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:30:56     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 348, in 
              self.add_context_menu_item(self.menu, 'Open Analysis', 'analysis', lambda: self.open_analysis(model_data))
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 552, in open_analysis
              self.analysis_doc_widget.configure_analysis(self.project, analysis, None)
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 78, in configure_analysis
              self.build_table()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 108, in build_table
              self.load_table_values()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:34:34     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:34:34     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 348, in 
              self.add_context_menu_item(self.menu, 'Open Analysis', 'analysis', lambda: self.open_analysis(model_data))
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 552, in open_analysis
              self.analysis_doc_widget.configure_analysis(self.project, analysis, None)
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 78, in configure_analysis
              self.build_table()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 108, in build_table
              self.load_table_values()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:34:46     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
             
2023-12-15T17:34:46     WARNING    Traceback (most recent call last):
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 348, in 
              self.add_context_menu_item(self.menu, 'Open Analysis', 'analysis', lambda: self.open_analysis(model_data))
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 552, in open_analysis
              self.analysis_doc_widget.configure_analysis(self.project, analysis, None)
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 78, in configure_analysis
              self.build_table()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 108, in build_table
              self.load_table_values()
              File "C:\Users/philip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 113, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by KellyMWhitehead** [comment]
Added two checks:

1) User warned and cannot proceed if selecting a featureless sample frame when creating a new analysis.
2) User warned and cannot proceed if trying to open an analysis with featureless sample frame (i.e. user deleted all sample frame features after creating the analysis.
