### ISSUE TITLE
Error when trying to Open Non-QRiS Geopackage

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#313]
I’m unable to open any of the Baily Flat DCEs in QRiS.  I’m getting the following error message.
 
<img width="454" alt="Screenshot 2024-01-10 at 3 18 06 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/c24f47a8-358d-4ff2-b800-f58e7fe7e81d">

 
2024-01-09T15:25:07     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 427, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 439, in open_qris_project
              result = check_metadata(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\update_metadata.py", line 74, in check_metadata
              c.execute(f"SELECT metadata FROM {layer}")
             sqlite3.OperationalError: no such column: metadata
             
2024-01-09T15:25:24     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 427, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 439, in open_qris_project
              result = check_metadata(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\update_metadata.py", line 74, in check_metadata
              c.execute(f"SELECT metadata FROM {layer}")
             sqlite3.OperationalError: no such column: metadata
             
2024-01-09T15:25:31     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 427, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 439, in open_qris_project
              result = check_metadata(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\update_metadata.py", line 74, in check_metadata
              c.execute(f"SELECT metadata FROM {layer}")
             sqlite3.OperationalError: no such column: metadata
             
2024-01-09T15:27:24     WARNING    Traceback (most recent call last):
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 427, in open_existing_project
              self.open_qris_project(dialog_return[0])
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 439, in open_qris_project
              result = check_metadata(db_path)
              File "C:\Users/ashallcross/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\update_metadata.py", line 74, in check_metadata
              c.execute(f"SELECT metadata FROM {layer}")
             sqlite3.OperationalError: no such column: metadata

**Comment by KellyMWhitehead** [comment]
Added a very basic check that looks for the 'projects' table and provides a message box if the gpkg is not a qris project. We can add other checks if we want, but this should catch basic gpkg vs qris files.
