### ISSUE TITLE
Promote Watershed Catchments to AOI throws error

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#493]
## Problem
When attempting to use the `Promote to AOI` command from watershed catchments, this **Exception: No features were imported. Check that the source and destination coordinate systems are the same and that the source and aoi mask geometries intersect.** is thrown. 

![image](https://github.com/user-attachments/assets/67847e09-4b61-4bd3-b769-84aaad3e5b66)

## Workaround
I was able to copy the layer feature to a temporary scratch layer and import from scratch. Although, only if scratch layer was located outside the QRiS Project layer group in layer tree. 

## Exception Message
```
Exception: No features were imported. Check that the source and destination coordinate systems are the same and that the source and aoi mask geometries intersect. 
Traceback (most recent call last):
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\import_feature_class.py", line 253, in finished
    raise self.exception
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\import_feature_class.py", line 221, in run
    raise Exception("No features were imported. Check that the source and destination coordinate systems are the same and that the source and aoi mask geometries intersect.")
Exception: No features were imported. Check that the source and destination coordinate systems are the same and that the source and aoi mask geometries intersect.


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.0-Maidenhead Maidenhead, 09951dc0 

Python Path:
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass83\etc\python
C:\Users\joemw\Documents
C:\Program Files\QGIS 3.36.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.36.0\bin
C:\Users\joemw\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\joemw\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mapflow\dialogs\widgets
C:\Users\joemw\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\joemw\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\riverscapes_viewer\src\..\wheels\rsxml-2.0.1-py3-none-any.whl
```

**Comment by joewheaton** [comment]
This appeared again. @Jdgilby also experienced.

**Comment by zburgert1997** [comment]
Haven't had this issue on the latest QRiS releases. Can we close this issue @joewheaton?
